[main]
debug = true          # debug mode
storage = "db.sqlite" # database file
timeout = 5           # db operation timeout (seconds)

[bot]
id = "123"
nick = "goBot"
token = "xxx"
url = "https://api.internal.myteam.mail.ru/bot/v1"
src = "https://github.com/z0rr0/gobot"
